import type { PropertyRow, UserProfile } from './types';

export const MOCK_PROPERTIES: PropertyRow[] = [
    {
        id: '1',
        title: 'ط´ظ‚ط© ظپط§ط®ط±ط© طھط·ظ„ ط¹ظ„ظ‰ ط§ظ„ط¨ط­ط±',
        description: 'ط´ظ‚ط© ط±ط§ط¦ط¹ط© ط¨ظپظٹظˆ ظ…ط¨ط§ط´ط± ط¹ظ„ظ‰ ط§ظ„ط¨ط­ط±طŒ ظ…ظƒظˆظ†ط© ظ…ظ† 3 ط؛ط±ظپ ظˆطµط§ظ„ط© ظƒط¨ظٹط±ط©. طھط´ط·ظٹط¨ ط³ظˆط¨ط± ظ„ظˆظƒط³ ظˆظ…ط¬ظ‡ط²ط© ط¨ط§ظ„ظƒط§ظ…ظ„.',
        price: 1500,
        price_unit: 'day',
        category: 'apartment',
        address: 'ط´ط§ط±ط¹ ط§ظ„ط¨ط­ط±طŒ ط¬ظ…طµط©',
        area: 'ظ…ظ†ط·ظ‚ط© ط§ظ„ظپظٹظ„ط§طھ',
        bedrooms: 3,
        bathrooms: 2,
        floor_area: 120,
        floor_number: 2,
        features: ['ظˆط§ظٹ ظپط§ظٹ', 'طھظƒظٹظٹظپ', 'ط´ط±ظپط©', 'ظ…ط·ط¨ط® ظ…ط¬ظ‡ط²', 'ظ…طµط¹ط¯'],
        images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80'],
        owner_id: 'owner-1',
        owner_name: 'ط§ظ„ط­ط§ط¬ ظ…ط­ظ…ط¯',
        owner_phone: '01012345678',
        status: 'available',
        is_verified: true,
        views_count: 150,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '2',
        title: 'ط´ط§ظ„ظٹط© ط£ط±ط¶ظٹ ط¨ط­ط¯ظٹظ‚ط© ط®ط§طµط©',
        description: 'ط´ط§ظ„ظٹط© ط¬ظ…ظٹظ„ ظ‚ط±ظٹط¨ ظ…ظ† ط§ظ„ط³ظˆظ‚ ظˆظ…ظ†ط·ظ‚ط© ط§ظ„ظ…ط·ط§ط¹ظ…. ط¨ظ‡ ط­ط¯ظٹظ‚ط© ط®ط§طµط© ظˆظ…ط¯ط®ظ„ ظ…ط³طھظ‚ظ„.',
        price: 800,
        price_unit: 'day',
        category: 'chalet',
        address: 'ظ…ظ†ط·ظ‚ط© 15 ظ…ط§ظٹظˆ',
        area: '15 ظ…ط§ظٹظˆ',
        bedrooms: 2,
        bathrooms: 1,
        floor_area: 80,
        floor_number: 0,
        features: ['ط­ط¯ظٹظ‚ط©', 'ظ‚ط±ظٹط¨ ظ…ظ† ط§ظ„ط®ط¯ظ…ط§طھ', 'ظ…ظˆظ‚ظپ ط³ظٹط§ط±ط§طھ'],
        images: ['https://images.unsplash.com/photo-1523217582562-09d0def993a6?auto=format&fit=crop&w=800&q=80'],
        owner_id: 'owner-2',
        owner_name: 'ط£ظ… ظƒط±ظٹظ…',
        owner_phone: '01122334455',
        status: 'available',
        is_verified: true,
        views_count: 85,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '3',
        title: 'ط³طھظˆط¯ظٹظˆ ط§ظ‚طھطµط§ط¯ظٹ ظ„ظ„ط·ظ„ط§ط¨',
        description: 'ط³طھظˆط¯ظٹظˆ طµط؛ظٹط± ظˆظ…ط±ظٹط­طŒ ظ…ظ†ط§ط³ط¨ ظ„ظ„ط·ظ„ط§ط¨ ط£ظˆ ط§ظ„ط£ظپط±ط§ط¯. ظ‚ط±ظٹط¨ ظ…ظ† ط§ظ„ط¬ط§ظ…ط¹ط©.',
        price: 3000,
        price_unit: 'month',
        category: 'studio',
        address: 'ط­ظٹ ط§ظ„ط´ط¨ط§ط¨',
        area: 'طھظ‚ط³ظٹظ… ط§ظ„ط´ط¨ط§ط¨',
        bedrooms: 1,
        bathrooms: 1,
        floor_area: 40,
        floor_number: 3,
        features: ['ط³ط±ظٹط±', 'ظ…ظƒطھط¨', 'ط¯ظˆظ„ط§ط¨'],
        images: ['https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=800&q=80'],
        owner_id: 'owner-1',
        owner_name: 'ط§ظ„ط­ط§ط¬ ظ…ط­ظ…ط¯',
        owner_phone: '01012345678',
        status: 'available',
        is_verified: false,
        views_count: 40,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: '4',
        title: 'ظپظٹظ„ط§ ظ…ط³طھظ‚ظ„ط© ظ„ظ„ط¹ط§ط¦ظ„ط§طھ ط§ظ„ظƒط¨ظٹط±ط©',
        description: 'ظپظٹظ„ط§ ط¯ظˆط±ظٹظ† ط¨ط­ط¯ظٹظ‚ط© ظˆط­ظ…ط§ظ… ط³ط¨ط§ط­ط©طŒ طھظƒظپظٹ ط¹ط§ط¦ظ„ط© ظƒط¨ظٹط±ط©. ظ‚ط±ظٹط¨ط© ظ…ظ† ط§ظ„ط¨ط­ط±.',
        price: 5000,
        price_unit: 'day',
        category: 'villa',
        address: 'ظ…ظ†ط·ظ‚ط© ط§ظ„ظپظٹظ„ط§طھ ط§ظ„ط¬ط¯ظٹط¯ط©',
        area: 'ظ…ظ†ط·ظ‚ط© ط§ظ„ظپظٹظ„ط§طھ',
        bedrooms: 5,
        bathrooms: 4,
        floor_area: 300,
        floor_number: 0,
        features: ['ط­ظ…ط§ظ… ط³ط¨ط§ط­ط©', 'ط­ط¯ظٹظ‚ط© ظƒط¨ظٹط±ط©', 'ط¬ط±ط§ط¬', 'طھظƒظٹظٹظپ ظ…ط±ظƒط²ظٹ'],
        images: ['https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=80'],
        owner_id: 'owner-3',
        owner_name: 'ط¯. ظ…ط­ظ…ظˆط¯',
        owner_phone: '01233445566',
        status: 'available',
        is_verified: true,
        views_count: 320,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    }
];

// In-memory storage for mock mode changes (resets on refresh)
export const _mockFavorites = new Set<string>();
export const _mockUnlocked = new Set<string>();

export const MOCK_PROFILES_BY_ID: Record<string, UserProfile> = {
    'mock-user-123': {
        id: 'mock-user-123',
        full_name: 'مستخدم تجريبي',
        avatar_url: null,
        phone: '01000000000',
        role: 'landlord',
        is_verified: true,
        is_admin: false,
    },
    'owner-1': {
        id: 'owner-1',
        full_name: 'الحاج محمد',
        avatar_url: null,
        phone: '01012345678',
        role: 'landlord',
        is_verified: true,
        is_admin: false,
    },
    'owner-2': {
        id: 'owner-2',
        full_name: 'أم كريم',
        avatar_url: null,
        phone: '01122334455',
        role: 'landlord',
        is_verified: true,
        is_admin: false,
    },
    'owner-3': {
        id: 'owner-3',
        full_name: 'د. محمود',
        avatar_url: null,
        phone: '01233445566',
        role: 'landlord',
        is_verified: true,
        is_admin: false,
    },
};
